### ISSUE TITLE
LED Frequency

### ISSUE THREAD

**Issue by bakerface** [FirstBuild/chillduino#32]
The LED driver chip in the refrigerator requires a frequency between `5,000` and `100,000` Hz. The default Arduino frequency is too low, preventing the refrigerator LED from ramping up.

**Comment by gillspice** [comment]
From the datasheet for the LED driver: "For optimum performance, use the PWM dimming frequency in the range of 5 kHz to 100 kHz."

This can be accomplished with this line:
TCCR4B = TCCR4B & 0b11111000 | 0x01;
